### ISSUE TITLE
Build from source - errors

### ISSUE THREAD

**Issue by Tymek** [open-source-labs/spearmint#104]
- Is `node-sass` needed? Building it makes installation problematic. `sass` should be enough
- There is no docs about building
- Build is failing with:
```
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
1 info using npm@7.6.3
2 info using node@v15.11.0
3 timing config:load:defaults Completed in 3ms
4 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 0ms
5 timing config:load:builtin Completed in 0ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/srv/spearmint/.npmrc Completed in 2ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/home/tczech/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 11ms
19 verbose npm-session ae0c8209f7a9e7df
20 timing npm:load Completed in 19ms
21 timing command:run Completed in 418698ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:378:20)
22 verbose stack     at maybeClose (node:internal/child_process:1067:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
23 verbose pkgid spearmint@0.5.0
24 verbose cwd /srv/spearmint
25 verbose Linux 5.9.16-1-MANJARO
26 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
27 verbose node v15.11.0
28 verbose npm  v7.6.3
29 error code 1
30 error path /srv/spearmint
31 error command failed
32 error command sh -c NODE_ENV=production npm run react-build && npm run electron-build
33 verbose exit 1
```

**Comment by taoantaoan** [comment]
Hi @Tymek,

Thanks for the message. You make a great point. We'll look in to this, and get back to you!

**Comment by taoantaoan** [comment]
Hi @Tymek,

Sorry for the delay. Lots of stuff going on behind the scenes! We've reviewed the issue that you flagged, and have decided to move from node-sass to dart-sass. Will be included in the next major release of Spearmint, scheduled for May 13, 2021. Let us know if this helps fix the error.

All the best,


-tHe SpEaRmInT tEaM

**Comment by Tymek** [comment]
Updated debug log for v0.6.0: 
<details><summary>
click to open

`0 verbose cli [
0 verbose cli   '/usr/bin/node',
0 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',...`

</summary>
<p>

```log
0 verbose cli [
0 verbose cli   '/usr/bin/node',
0 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'rebuild',
0 verbose cli   'fibers@5.0.0',
0 verbose cli   'node-pty@0.10.1'
0 verbose cli ]
1 info using npm@7.11.2
2 info using node@v16.0.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 2ms
9 timing config:load:file:/srv/oss/spearmint/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/home/tczech/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 11ms
19 timing npm:load:configload Completed in 11ms
20 timing npm:load:setTitle Completed in 1ms
21 timing npm:load:setupLog Completed in 1ms
22 timing npm:load:cleanupLog Completed in 4ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 0ms
25 timing npm:load Completed in 18ms
26 timing config:load:flatten Completed in 2ms
27 timing arborist:ctor Completed in 1ms
28 timing arborist:ctor Completed in 0ms
29 timing build:queue Completed in 1ms
30 info run fibers@5.0.0 install node_modules/fibers node build.js || nodejs build.js
31 info run node-pty@0.10.1 install node_modules/node-pty node scripts/install.js
32 info run node-pty@0.10.1 install { code: 1, signal: null }
33 timing command:rebuild Completed in 2642ms
34 verbose stack Error: command failed
34 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
34 verbose stack     at ChildProcess.emit (node:events:365:28)
34 verbose stack     at maybeClose (node:internal/child_process:1067:16)
34 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
35 verbose pkgid node-pty@0.10.1
36 verbose cwd /srv/oss/spearmint
37 verbose Linux 5.9.16-1-MANJARO
38 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "rebuild" "fibers@5.0.0" "node-pty@0.10.1"
39 verbose node v16.0.0
40 verbose npm  v7.11.2
41 error code 1
42 error path /srv/oss/spearmint/node_modules/node-pty
43 error command failed
44 error command sh -c node scripts/install.js
45 error sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
45 error gyp info it worked if it ends with ok
45 error gyp info using node-gyp@7.1.2
45 error gyp info using node@16.0.0 | linux | x64
45 error gyp info find Python using Python version 3.9.4 found at "/usr/bin/python3"
45 error (node:231136) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
45 error (Use `node --trace-deprecation ...` to show where the warning was created)
45 error gyp info spawn /usr/bin/python3
45 error gyp info spawn args [
45 error gyp info spawn args   '/srv/oss/spearmint/node_modules/node-gyp/gyp/gyp_main.py',
45 error gyp info spawn args   'binding.gyp',
45 error gyp info spawn args   '-f',
45 error gyp info spawn args   'make',
45 error gyp info spawn args   '-I',
45 error gyp info spawn args   '/srv/oss/spearmint/node_modules/node-pty/build/config.gypi',
45 error gyp info spawn args   '-I',
45 error gyp info spawn args   '/srv/oss/spearmint/node_modules/node-gyp/addon.gypi',
45 error gyp info spawn args   '-I',
45 error gyp info spawn args   '/home/tczech/.electron-gyp/12.0.7/include/node/common.gypi',
45 error gyp info spawn args   '-Dlibrary=shared_library',
45 error gyp info spawn args   '-Dvisibility=default',
45 error gyp info spawn args   '-Dnode_root_dir=/home/tczech/.electron-gyp/12.0.7',
45 error gyp info spawn args   '-Dnode_gyp_dir=/srv/oss/spearmint/node_modules/node-gyp',
45 error gyp info spawn args   '-Dnode_lib_file=/home/tczech/.electron-gyp/12.0.7/<(target_arch)/node.lib',
45 error gyp info spawn args   '-Dmodule_root_dir=/srv/oss/spearmint/node_modules/node-pty',
45 error gyp info spawn args   '-Dnode_engine=v8',
45 error gyp info spawn args   '--depth=.',
45 error gyp info spawn args   '--no-parallel',
45 error gyp info spawn args   '--generator-output',
45 error gyp info spawn args   'build',
45 error gyp info spawn args   '-Goutput_dir=.'
45 error gyp info spawn args ]
45 error /bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
45 error gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
45 error gyp ERR! configure error
45 error gyp ERR! stack Error: `gyp` failed with exit code: 1
45 error gyp ERR! stack     at ChildProcess.onCpExit (/srv/oss/spearmint/node_modules/node-gyp/lib/configure.js:351:16)
45 error gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
45 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
45 error gyp ERR! System Linux 5.9.16-1-MANJARO
45 error gyp ERR! command "/usr/bin/node" "/srv/oss/spearmint/node_modules/.bin/node-gyp" "rebuild"
45 error gyp ERR! cwd /srv/oss/spearmint/node_modules/node-pty
45 error gyp ERR! node -v v16.0.0
45 error gyp ERR! node-gyp -v v7.1.2
45 error gyp ERR! not ok
46 verbose exit 1
```

</p>
</details>
